import { GDGEvent, Registration } from "./types";

export const mockEvents: GDGEvent[] = [
  {
    id: "1",
    title: "Google I/O Extended 2026",
    description: "Join us for a local viewing party of Google I/O 2026! Watch the keynote together, participate in hands-on codelabs, and network with fellow developers. This event is perfect for anyone interested in the latest Google technologies including Android, Web, Cloud, and AI/ML.",
    department: "All Departments",
    startDate: "2026-05-15T09:00:00",
    endDate: "2026-05-15T18:00:00",
    location: "Main Auditorium, Tech Campus",
    locationType: "offline",
    image: "",
    organizer: "GDG On Campus",
    gallery: [],
    createdAt: "2026-03-01T10:00:00",
  },
  {
    id: "2",
    title: "Flutter Forward Workshop",
    description: "A hands-on workshop on building beautiful cross-platform apps with Flutter 4. Learn about the latest widgets, state management patterns, and how to deploy to mobile, web, and desktop from a single codebase.",
    department: "CSE, IT",
    startDate: "2026-04-20T10:00:00",
    endDate: "2026-04-20T16:00:00",
    location: "https://meet.google.com/abc-defg-hij",
    locationType: "online",
    image: "",
    organizer: "Flutter Team Lead",
    gallery: [],
    createdAt: "2026-03-10T10:00:00",
  },
  {
    id: "3",
    title: "Cloud Study Jam: GCP Essentials",
    description: "Get started with Google Cloud Platform! This study jam covers Compute Engine, Cloud Storage, BigQuery, and Kubernetes basics. Earn skill badges and Google Cloud credits upon completion.",
    department: "CSE, IT, ECE",
    startDate: "2026-04-10T14:00:00",
    endDate: "2026-04-10T17:00:00",
    location: "Lab 301, CS Building",
    locationType: "offline",
    image: "",
    organizer: "Cloud Lead",
    gallery: [],
    createdAt: "2026-03-05T10:00:00",
  },
  {
    id: "4",
    title: "Android Dev Summit Watch Party",
    description: "Watch the Android Dev Summit live stream with the community. Explore Jetpack Compose updates, Material You theming, and performance improvements in Android 16.",
    department: "CSE, IT",
    startDate: "2026-06-01T10:00:00",
    endDate: "2026-06-01T15:00:00",
    location: "Seminar Hall B",
    locationType: "offline",
    image: "",
    organizer: "Android Lead",
    gallery: [],
    createdAt: "2026-03-15T10:00:00",
  },
  {
    id: "5",
    title: "AI/ML Bootcamp: TensorFlow & Gemini",
    description: "Deep dive into machine learning with TensorFlow and the Gemini API. Build real-world AI applications, learn prompt engineering, and explore multimodal AI capabilities.",
    department: "All Departments",
    startDate: "2026-04-25T09:00:00",
    endDate: "2026-04-26T17:00:00",
    location: "Innovation Center",
    locationType: "offline",
    image: "",
    organizer: "ML Lead",
    gallery: [],
    createdAt: "2026-03-20T10:00:00",
  },
  {
    id: "6",
    title: "Web Dev Hackathon: Build with Firebase",
    description: "24-hour hackathon focused on building web applications using Firebase, Angular, and Google APIs. Great prizes await the top 3 teams!",
    department: "CSE, IT",
    startDate: "2026-05-10T08:00:00",
    endDate: "2026-05-11T08:00:00",
    location: "Startup Hub, 2nd Floor",
    locationType: "offline",
    image: "",
    organizer: "Web Lead",
    gallery: [],
    createdAt: "2026-03-25T10:00:00",
  },
];

export const mockRegistrations: Registration[] = [
  {
    id: "r1",
    eventId: "1",
    name: "Alice Johnson",
    email: "alice@example.com",
    phone: "9876543210",
    college: "Tech University",
    department: "CSE",
    rsvp: "going",
    createdAt: "2026-03-28T10:00:00",
  },
  {
    id: "r2",
    eventId: "1",
    name: "Bob Smith",
    email: "bob@example.com",
    phone: "9876543211",
    college: "Tech University",
    department: "IT",
    rsvp: "going",
    createdAt: "2026-03-28T11:00:00",
  },
  {
    id: "r3",
    eventId: "2",
    name: "Carol Lee",
    email: "carol@example.com",
    phone: "9876543212",
    college: "Engineering College",
    department: "CSE",
    rsvp: "going",
    createdAt: "2026-03-29T09:00:00",
  },
];
